homepage: "https://json.jodd.org/"
language: jvm
primary_contact: ""
auto_ccs:
  - "meumertzheim@code-intelligence.com"
fuzzing_engines:
  - libfuzzer
main_repo: "https://github.com/oblac/jodd-json"
sanitizers:
  - address
